services:
  pigeon:
    container_name: pigeon
    build:
      context: .
      dockerfile: Dockerfile.pigeon
    volumes:
      - ./volumes/pigeon-data:/peerBench/data
    env_file:
      - path: .env
        required: false
      - path: .env.docker
        required: false
      - path: apps/pigeon/.env
        required: false
      - path: apps/pigeon/.env.docker
        required: false
    restart: unless-stopped
