services:
  webapp:
    build:
      context: .
      dockerfile: Dockerfile.webapp
    ports:
      - "3110:3000"
    env_file:
      - path: .env
        required: false
      - path: .env.docker
        required: false
      - path: apps/webapp/.env
        required: false
      - path: apps/webapp/.env.docker
        required: false
    restart: unless-stopped
